package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Consumer generated by hbm2java
 */
public class Consumer  implements java.io.Serializable {


     private Long consId;
     private String consName;
     private String consAddress;
     private String consCity;
     private String consContactNo;
     private String consEmail;
     private Set<RetailOrders> retailOrderses = new HashSet<RetailOrders>(0);

    public Consumer() {
    }

    public Consumer(String consName, String consAddress, String consCity, String consContactNo, String consEmail, Set<RetailOrders> retailOrderses) {
       this.consName = consName;
       this.consAddress = consAddress;
       this.consCity = consCity;
       this.consContactNo = consContactNo;
       this.consEmail = consEmail;
       this.retailOrderses = retailOrderses;
    }
   
    public Long getConsId() {
        return this.consId;
    }
    
    public void setConsId(Long consId) {
        this.consId = consId;
    }
    public String getConsName() {
        return this.consName;
    }
    
    public void setConsName(String consName) {
        this.consName = consName;
    }
    public String getConsAddress() {
        return this.consAddress;
    }
    
    public void setConsAddress(String consAddress) {
        this.consAddress = consAddress;
    }
    public String getConsCity() {
        return this.consCity;
    }
    
    public void setConsCity(String consCity) {
        this.consCity = consCity;
    }
    public String getConsContactNo() {
        return this.consContactNo;
    }
    
    public void setConsContactNo(String consContactNo) {
        this.consContactNo = consContactNo;
    }
    public String getConsEmail() {
        return this.consEmail;
    }
    
    public void setConsEmail(String consEmail) {
        this.consEmail = consEmail;
    }
    public Set<RetailOrders> getRetailOrderses() {
        return this.retailOrderses;
    }
    
    public void setRetailOrderses(Set<RetailOrders> retailOrderses) {
        this.retailOrderses = retailOrderses;
    }




}


