package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RetailerAvailableStockHistory generated by hbm2java
 */
public class RetailerAvailableStockHistory  implements java.io.Serializable {


     private Long rtAvStockHistoryId;
     private long rtId;
     private long rtProdId;
     private Integer rtStockAvailableQnty;
     private Date rtHistoryDate;

    public RetailerAvailableStockHistory() {
    }

	
    public RetailerAvailableStockHistory(long rtId, long rtProdId, Date rtHistoryDate) {
        this.rtId = rtId;
        this.rtProdId = rtProdId;
        this.rtHistoryDate = rtHistoryDate;
    }
    public RetailerAvailableStockHistory(long rtId, long rtProdId, Integer rtStockAvailableQnty, Date rtHistoryDate) {
       this.rtId = rtId;
       this.rtProdId = rtProdId;
       this.rtStockAvailableQnty = rtStockAvailableQnty;
       this.rtHistoryDate = rtHistoryDate;
    }
   
    public Long getRtAvStockHistoryId() {
        return this.rtAvStockHistoryId;
    }
    
    public void setRtAvStockHistoryId(Long rtAvStockHistoryId) {
        this.rtAvStockHistoryId = rtAvStockHistoryId;
    }
    public long getRtId() {
        return this.rtId;
    }
    
    public void setRtId(long rtId) {
        this.rtId = rtId;
    }
    public long getRtProdId() {
        return this.rtProdId;
    }
    
    public void setRtProdId(long rtProdId) {
        this.rtProdId = rtProdId;
    }
    public Integer getRtStockAvailableQnty() {
        return this.rtStockAvailableQnty;
    }
    
    public void setRtStockAvailableQnty(Integer rtStockAvailableQnty) {
        this.rtStockAvailableQnty = rtStockAvailableQnty;
    }
    public Date getRtHistoryDate() {
        return this.rtHistoryDate;
    }
    
    public void setRtHistoryDate(Date rtHistoryDate) {
        this.rtHistoryDate = rtHistoryDate;
    }




}


