package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RetailProducts generated by hbm2java
 */
public class RetailProducts  implements java.io.Serializable {


     private Long rtProdId;
     private String rtProdName;
     private String rtProdDesc;
     private String rtProdCatg;
     private String rtProdSubCatg;
     private Long rtDependProdId;
     private Set<RetailerProductsStock> retailerProductsStocks = new HashSet<RetailerProductsStock>(0);

    public RetailProducts() {
    }

    public RetailProducts(String rtProdName, String rtProdDesc, String rtProdCatg, String rtProdSubCatg, Long rtDependProdId, Set<RetailerProductsStock> retailerProductsStocks) {
       this.rtProdName = rtProdName;
       this.rtProdDesc = rtProdDesc;
       this.rtProdCatg = rtProdCatg;
       this.rtProdSubCatg = rtProdSubCatg;
       this.rtDependProdId = rtDependProdId;
       this.retailerProductsStocks = retailerProductsStocks;
    }
   
    public Long getRtProdId() {
        return this.rtProdId;
    }
    
    public void setRtProdId(Long rtProdId) {
        this.rtProdId = rtProdId;
    }
    public String getRtProdName() {
        return this.rtProdName;
    }
    
    public void setRtProdName(String rtProdName) {
        this.rtProdName = rtProdName;
    }
    public String getRtProdDesc() {
        return this.rtProdDesc;
    }
    
    public void setRtProdDesc(String rtProdDesc) {
        this.rtProdDesc = rtProdDesc;
    }
    public String getRtProdCatg() {
        return this.rtProdCatg;
    }
    
    public void setRtProdCatg(String rtProdCatg) {
        this.rtProdCatg = rtProdCatg;
    }
    public String getRtProdSubCatg() {
        return this.rtProdSubCatg;
    }
    
    public void setRtProdSubCatg(String rtProdSubCatg) {
        this.rtProdSubCatg = rtProdSubCatg;
    }
    public Long getRtDependProdId() {
        return this.rtDependProdId;
    }
    
    public void setRtDependProdId(Long rtDependProdId) {
        this.rtDependProdId = rtDependProdId;
    }
    public Set<RetailerProductsStock> getRetailerProductsStocks() {
        return this.retailerProductsStocks;
    }
    
    public void setRetailerProductsStocks(Set<RetailerProductsStock> retailerProductsStocks) {
        this.retailerProductsStocks = retailerProductsStocks;
    }




}


