package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * RetailerProductsStock generated by hbm2java
 */
public class RetailerProductsStock  implements java.io.Serializable {


     private RetailerProductsStockId id;
     private Retailer retailer;
     private RetailProducts retailProducts;
     private Integer rtStockUpThrQnty;
     private Integer rtStockLowThrQnty;
     private Integer rtStockAvailableQnty;
     private Integer rtStockOrderedQnty;
     private Double rtProdCostPrice;
     private Double rtProdSellPrice;
     private Double rtProdMarginPrice;
     private String rtProdPriceCurrency;
     private Float rtProdMarginPercentage;
     private Integer rtMaxDeliveryDays;
     private Integer rtMinDeliveryDays;
     private Integer rtMaxQntyStorage;
     private Integer rtProdQntySold;
     private Set<RetailOrders> retailOrderses = new HashSet<RetailOrders>(0);

    public RetailerProductsStock() {
    }

	
    public RetailerProductsStock(RetailerProductsStockId id, Retailer retailer, RetailProducts retailProducts) {
        this.id = id;
        this.retailer = retailer;
        this.retailProducts = retailProducts;
    }
    public RetailerProductsStock(RetailerProductsStockId id, Retailer retailer, RetailProducts retailProducts, Integer rtStockUpThrQnty, Integer rtStockLowThrQnty, Integer rtStockAvailableQnty, Integer rtStockOrderedQnty, Double rtProdCostPrice, Double rtProdSellPrice, Double rtProdMarginPrice, String rtProdPriceCurrency, Float rtProdMarginPercentage, Integer rtMaxDeliveryDays, Integer rtMinDeliveryDays, Integer rtMaxQntyStorage, Integer rtProdQntySold, Set<RetailOrders> retailOrderses) {
       this.id = id;
       this.retailer = retailer;
       this.retailProducts = retailProducts;
       this.rtStockUpThrQnty = rtStockUpThrQnty;
       this.rtStockLowThrQnty = rtStockLowThrQnty;
       this.rtStockAvailableQnty = rtStockAvailableQnty;
       this.rtStockOrderedQnty = rtStockOrderedQnty;
       this.rtProdCostPrice = rtProdCostPrice;
       this.rtProdSellPrice = rtProdSellPrice;
       this.rtProdMarginPrice = rtProdMarginPrice;
       this.rtProdPriceCurrency = rtProdPriceCurrency;
       this.rtProdMarginPercentage = rtProdMarginPercentage;
       this.rtMaxDeliveryDays = rtMaxDeliveryDays;
       this.rtMinDeliveryDays = rtMinDeliveryDays;
       this.rtMaxQntyStorage = rtMaxQntyStorage;
       this.rtProdQntySold = rtProdQntySold;
       this.retailOrderses = retailOrderses;
    }
   
    public RetailerProductsStockId getId() {
        return this.id;
    }
    
    public void setId(RetailerProductsStockId id) {
        this.id = id;
    }
    public Retailer getRetailer() {
        return this.retailer;
    }
    
    public void setRetailer(Retailer retailer) {
        this.retailer = retailer;
    }
    public RetailProducts getRetailProducts() {
        return this.retailProducts;
    }
    
    public void setRetailProducts(RetailProducts retailProducts) {
        this.retailProducts = retailProducts;
    }
    public Integer getRtStockUpThrQnty() {
        return this.rtStockUpThrQnty;
    }
    
    public void setRtStockUpThrQnty(Integer rtStockUpThrQnty) {
        this.rtStockUpThrQnty = rtStockUpThrQnty;
    }
    public Integer getRtStockLowThrQnty() {
        return this.rtStockLowThrQnty;
    }
    
    public void setRtStockLowThrQnty(Integer rtStockLowThrQnty) {
        this.rtStockLowThrQnty = rtStockLowThrQnty;
    }
    public Integer getRtStockAvailableQnty() {
        return this.rtStockAvailableQnty;
    }
    
    public void setRtStockAvailableQnty(Integer rtStockAvailableQnty) {
        this.rtStockAvailableQnty = rtStockAvailableQnty;
    }
    public Integer getRtStockOrderedQnty() {
        return this.rtStockOrderedQnty;
    }
    
    public void setRtStockOrderedQnty(Integer rtStockOrderedQnty) {
        this.rtStockOrderedQnty = rtStockOrderedQnty;
    }
    public Double getRtProdCostPrice() {
        return this.rtProdCostPrice;
    }
    
    public void setRtProdCostPrice(Double rtProdCostPrice) {
        this.rtProdCostPrice = rtProdCostPrice;
    }
    public Double getRtProdSellPrice() {
        return this.rtProdSellPrice;
    }
    
    public void setRtProdSellPrice(Double rtProdSellPrice) {
        this.rtProdSellPrice = rtProdSellPrice;
    }
    public Double getRtProdMarginPrice() {
        return this.rtProdMarginPrice;
    }
    
    public void setRtProdMarginPrice(Double rtProdMarginPrice) {
        this.rtProdMarginPrice = rtProdMarginPrice;
    }
    public String getRtProdPriceCurrency() {
        return this.rtProdPriceCurrency;
    }
    
    public void setRtProdPriceCurrency(String rtProdPriceCurrency) {
        this.rtProdPriceCurrency = rtProdPriceCurrency;
    }
    public Float getRtProdMarginPercentage() {
        return this.rtProdMarginPercentage;
    }
    
    public void setRtProdMarginPercentage(Float rtProdMarginPercentage) {
        this.rtProdMarginPercentage = rtProdMarginPercentage;
    }
    public Integer getRtMaxDeliveryDays() {
        return this.rtMaxDeliveryDays;
    }
    
    public void setRtMaxDeliveryDays(Integer rtMaxDeliveryDays) {
        this.rtMaxDeliveryDays = rtMaxDeliveryDays;
    }
    public Integer getRtMinDeliveryDays() {
        return this.rtMinDeliveryDays;
    }
    
    public void setRtMinDeliveryDays(Integer rtMinDeliveryDays) {
        this.rtMinDeliveryDays = rtMinDeliveryDays;
    }
    public Integer getRtMaxQntyStorage() {
        return this.rtMaxQntyStorage;
    }
    
    public void setRtMaxQntyStorage(Integer rtMaxQntyStorage) {
        this.rtMaxQntyStorage = rtMaxQntyStorage;
    }
    public Integer getRtProdQntySold() {
        return this.rtProdQntySold;
    }
    
    public void setRtProdQntySold(Integer rtProdQntySold) {
        this.rtProdQntySold = rtProdQntySold;
    }
    public Set<RetailOrders> getRetailOrderses() {
        return this.retailOrderses;
    }
    
    public void setRetailOrderses(Set<RetailOrders> retailOrderses) {
        this.retailOrderses = retailOrderses;
    }




}


