package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA



/**
 * RetailerProductsStockId generated by hbm2java
 */
public class RetailerProductsStockId  implements java.io.Serializable {


     private long rtId;
     private long rtProdId;

    public RetailerProductsStockId() {
    }

    public RetailerProductsStockId(long rtId, long rtProdId) {
       this.rtId = rtId;
       this.rtProdId = rtProdId;
    }
   
    public long getRtId() {
        return this.rtId;
    }
    
    public void setRtId(long rtId) {
        this.rtId = rtId;
    }
    public long getRtProdId() {
        return this.rtProdId;
    }
    
    public void setRtProdId(long rtProdId) {
        this.rtProdId = rtProdId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RetailerProductsStockId) ) return false;
		 RetailerProductsStockId castOther = ( RetailerProductsStockId ) other; 
         
		 return (this.getRtId()==castOther.getRtId())
 && (this.getRtProdId()==castOther.getRtProdId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getRtId();
         result = 37 * result + (int) this.getRtProdId();
         return result;
   }   


}


