package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * RetailDelivery generated by hbm2java
 */
public class RetailDelivery  implements java.io.Serializable {


     private Long rtDeliveryId;
     private RetailOrders retailOrders;
     private Date rtDeliveryDate;
     private Integer rtNoOfDays;

    public RetailDelivery() {
    }

	
    public RetailDelivery(RetailOrders retailOrders) {
        this.retailOrders = retailOrders;
    }
    public RetailDelivery(RetailOrders retailOrders, Date rtDeliveryDate, Integer rtNoOfDays) {
       this.retailOrders = retailOrders;
       this.rtDeliveryDate = rtDeliveryDate;
       this.rtNoOfDays = rtNoOfDays;
    }
   
    public Long getRtDeliveryId() {
        return this.rtDeliveryId;
    }
    
    public void setRtDeliveryId(Long rtDeliveryId) {
        this.rtDeliveryId = rtDeliveryId;
    }
    public RetailOrders getRetailOrders() {
        return this.retailOrders;
    }
    
    public void setRetailOrders(RetailOrders retailOrders) {
        this.retailOrders = retailOrders;
    }
    public Date getRtDeliveryDate() {
        return this.rtDeliveryDate;
    }
    
    public void setRtDeliveryDate(Date rtDeliveryDate) {
        this.rtDeliveryDate = rtDeliveryDate;
    }
    public Integer getRtNoOfDays() {
        return this.rtNoOfDays;
    }
    
    public void setRtNoOfDays(Integer rtNoOfDays) {
        this.rtNoOfDays = rtNoOfDays;
    }




}


