package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WholesaleOrders generated by hbm2java
 */
public class WholesaleOrders  implements java.io.Serializable {


     private Long whOrdNo;
     private Retailer retailer;
     private WholesaleOrderStatus wholesaleOrderStatus;
     private WholesalerProductsStock wholesalerProductsStock;
     private Integer whOrdQnty;
     private Double whOrdPrice;
     private Date whOrderDate;
     private Set<WholesaleDelivery> wholesaleDeliveries = new HashSet<WholesaleDelivery>(0);

    public WholesaleOrders() {
    }

	
    public WholesaleOrders(Retailer retailer, WholesaleOrderStatus wholesaleOrderStatus, WholesalerProductsStock wholesalerProductsStock) {
        this.retailer = retailer;
        this.wholesaleOrderStatus = wholesaleOrderStatus;
        this.wholesalerProductsStock = wholesalerProductsStock;
    }
    public WholesaleOrders(Retailer retailer, WholesaleOrderStatus wholesaleOrderStatus, WholesalerProductsStock wholesalerProductsStock, Integer whOrdQnty, Double whOrdPrice, Date whOrderDate, Set<WholesaleDelivery> wholesaleDeliveries) {
       this.retailer = retailer;
       this.wholesaleOrderStatus = wholesaleOrderStatus;
       this.wholesalerProductsStock = wholesalerProductsStock;
       this.whOrdQnty = whOrdQnty;
       this.whOrdPrice = whOrdPrice;
       this.whOrderDate = whOrderDate;
       this.wholesaleDeliveries = wholesaleDeliveries;
    }
   
    public Long getWhOrdNo() {
        return this.whOrdNo;
    }
    
    public void setWhOrdNo(Long whOrdNo) {
        this.whOrdNo = whOrdNo;
    }
    public Retailer getRetailer() {
        return this.retailer;
    }
    
    public void setRetailer(Retailer retailer) {
        this.retailer = retailer;
    }
    public WholesaleOrderStatus getWholesaleOrderStatus() {
        return this.wholesaleOrderStatus;
    }
    
    public void setWholesaleOrderStatus(WholesaleOrderStatus wholesaleOrderStatus) {
        this.wholesaleOrderStatus = wholesaleOrderStatus;
    }
    public WholesalerProductsStock getWholesalerProductsStock() {
        return this.wholesalerProductsStock;
    }
    
    public void setWholesalerProductsStock(WholesalerProductsStock wholesalerProductsStock) {
        this.wholesalerProductsStock = wholesalerProductsStock;
    }
    public Integer getWhOrdQnty() {
        return this.whOrdQnty;
    }
    
    public void setWhOrdQnty(Integer whOrdQnty) {
        this.whOrdQnty = whOrdQnty;
    }
    public Double getWhOrdPrice() {
        return this.whOrdPrice;
    }
    
    public void setWhOrdPrice(Double whOrdPrice) {
        this.whOrdPrice = whOrdPrice;
    }
    public Date getWhOrderDate() {
        return this.whOrderDate;
    }
    
    public void setWhOrderDate(Date whOrderDate) {
        this.whOrderDate = whOrderDate;
    }
    public Set<WholesaleDelivery> getWholesaleDeliveries() {
        return this.wholesaleDeliveries;
    }
    
    public void setWholesaleDeliveries(Set<WholesaleDelivery> wholesaleDeliveries) {
        this.wholesaleDeliveries = wholesaleDeliveries;
    }




}


