package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * WholesaleOrderStatus generated by hbm2java
 */
public class WholesaleOrderStatus  implements java.io.Serializable {


     private Integer whStatusId;
     private String whStatusC;
     private String whStatusDesc;
     private Set<WholesaleOrders> wholesaleOrderses = new HashSet<WholesaleOrders>(0);

    public WholesaleOrderStatus() {
    }

    public WholesaleOrderStatus(String whStatusC, String whStatusDesc, Set<WholesaleOrders> wholesaleOrderses) {
       this.whStatusC = whStatusC;
       this.whStatusDesc = whStatusDesc;
       this.wholesaleOrderses = wholesaleOrderses;
    }
   
    public Integer getWhStatusId() {
        return this.whStatusId;
    }
    
    public void setWhStatusId(Integer whStatusId) {
        this.whStatusId = whStatusId;
    }
    public String getWhStatusC() {
        return this.whStatusC;
    }
    
    public void setWhStatusC(String whStatusC) {
        this.whStatusC = whStatusC;
    }
    public String getWhStatusDesc() {
        return this.whStatusDesc;
    }
    
    public void setWhStatusDesc(String whStatusDesc) {
        this.whStatusDesc = whStatusDesc;
    }
    public Set<WholesaleOrders> getWholesaleOrderses() {
        return this.wholesaleOrderses;
    }
    
    public void setWholesaleOrderses(Set<WholesaleOrders> wholesaleOrderses) {
        this.wholesaleOrderses = wholesaleOrderses;
    }




}


