package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * WholesalerProductsStock generated by hbm2java
 */
public class WholesalerProductsStock  implements java.io.Serializable {


     private WholesalerProductsStockId id;
     private Wholesaler wholesaler;
     private WholesaleProducts wholesaleProducts;
     private Integer whStockUpThrQnty;
     private Integer whStockLowThrQnty;
     private Integer whStockAvailableQnty;
     private Integer whStockOrderedQnty;
     private Double whProdCostPrice;
     private Double whProdSellPrice;
     private Double whProdMarginPrice;
     private String whProdPriceCurrency;
     private Float whProdMarginPercentage;
     private Integer whMaxDeliveryDays;
     private Integer whMinDeliveryDays;
     private Integer whMaxQntyStorage;
     private Integer whProdQntySold;
     private Set<WholesaleOrders> wholesaleOrderses = new HashSet<WholesaleOrders>(0);

    public WholesalerProductsStock() {
    }

	
    public WholesalerProductsStock(WholesalerProductsStockId id, Wholesaler wholesaler, WholesaleProducts wholesaleProducts) {
        this.id = id;
        this.wholesaler = wholesaler;
        this.wholesaleProducts = wholesaleProducts;
    }
    public WholesalerProductsStock(WholesalerProductsStockId id, Wholesaler wholesaler, WholesaleProducts wholesaleProducts, Integer whStockUpThrQnty, Integer whStockLowThrQnty, Integer whStockAvailableQnty, Integer whStockOrderedQnty, Double whProdCostPrice, Double whProdSellPrice, Double whProdMarginPrice, String whProdPriceCurrency, Float whProdMarginPercentage, Integer whMaxDeliveryDays, Integer whMinDeliveryDays, Integer whMaxQntyStorage, Integer whProdQntySold, Set<WholesaleOrders> wholesaleOrderses) {
       this.id = id;
       this.wholesaler = wholesaler;
       this.wholesaleProducts = wholesaleProducts;
       this.whStockUpThrQnty = whStockUpThrQnty;
       this.whStockLowThrQnty = whStockLowThrQnty;
       this.whStockAvailableQnty = whStockAvailableQnty;
       this.whStockOrderedQnty = whStockOrderedQnty;
       this.whProdCostPrice = whProdCostPrice;
       this.whProdSellPrice = whProdSellPrice;
       this.whProdMarginPrice = whProdMarginPrice;
       this.whProdPriceCurrency = whProdPriceCurrency;
       this.whProdMarginPercentage = whProdMarginPercentage;
       this.whMaxDeliveryDays = whMaxDeliveryDays;
       this.whMinDeliveryDays = whMinDeliveryDays;
       this.whMaxQntyStorage = whMaxQntyStorage;
       this.whProdQntySold = whProdQntySold;
       this.wholesaleOrderses = wholesaleOrderses;
    }
   
    public WholesalerProductsStockId getId() {
        return this.id;
    }
    
    public void setId(WholesalerProductsStockId id) {
        this.id = id;
    }
    public Wholesaler getWholesaler() {
        return this.wholesaler;
    }
    
    public void setWholesaler(Wholesaler wholesaler) {
        this.wholesaler = wholesaler;
    }
    public WholesaleProducts getWholesaleProducts() {
        return this.wholesaleProducts;
    }
    
    public void setWholesaleProducts(WholesaleProducts wholesaleProducts) {
        this.wholesaleProducts = wholesaleProducts;
    }
    public Integer getWhStockUpThrQnty() {
        return this.whStockUpThrQnty;
    }
    
    public void setWhStockUpThrQnty(Integer whStockUpThrQnty) {
        this.whStockUpThrQnty = whStockUpThrQnty;
    }
    public Integer getWhStockLowThrQnty() {
        return this.whStockLowThrQnty;
    }
    
    public void setWhStockLowThrQnty(Integer whStockLowThrQnty) {
        this.whStockLowThrQnty = whStockLowThrQnty;
    }
    public Integer getWhStockAvailableQnty() {
        return this.whStockAvailableQnty;
    }
    
    public void setWhStockAvailableQnty(Integer whStockAvailableQnty) {
        this.whStockAvailableQnty = whStockAvailableQnty;
    }
    public Integer getWhStockOrderedQnty() {
        return this.whStockOrderedQnty;
    }
    
    public void setWhStockOrderedQnty(Integer whStockOrderedQnty) {
        this.whStockOrderedQnty = whStockOrderedQnty;
    }
    public Double getWhProdCostPrice() {
        return this.whProdCostPrice;
    }
    
    public void setWhProdCostPrice(Double whProdCostPrice) {
        this.whProdCostPrice = whProdCostPrice;
    }
    public Double getWhProdSellPrice() {
        return this.whProdSellPrice;
    }
    
    public void setWhProdSellPrice(Double whProdSellPrice) {
        this.whProdSellPrice = whProdSellPrice;
    }
    public Double getWhProdMarginPrice() {
        return this.whProdMarginPrice;
    }
    
    public void setWhProdMarginPrice(Double whProdMarginPrice) {
        this.whProdMarginPrice = whProdMarginPrice;
    }
    public String getWhProdPriceCurrency() {
        return this.whProdPriceCurrency;
    }
    
    public void setWhProdPriceCurrency(String whProdPriceCurrency) {
        this.whProdPriceCurrency = whProdPriceCurrency;
    }
    public Float getWhProdMarginPercentage() {
        return this.whProdMarginPercentage;
    }
    
    public void setWhProdMarginPercentage(Float whProdMarginPercentage) {
        this.whProdMarginPercentage = whProdMarginPercentage;
    }
    public Integer getWhMaxDeliveryDays() {
        return this.whMaxDeliveryDays;
    }
    
    public void setWhMaxDeliveryDays(Integer whMaxDeliveryDays) {
        this.whMaxDeliveryDays = whMaxDeliveryDays;
    }
    public Integer getWhMinDeliveryDays() {
        return this.whMinDeliveryDays;
    }
    
    public void setWhMinDeliveryDays(Integer whMinDeliveryDays) {
        this.whMinDeliveryDays = whMinDeliveryDays;
    }
    public Integer getWhMaxQntyStorage() {
        return this.whMaxQntyStorage;
    }
    
    public void setWhMaxQntyStorage(Integer whMaxQntyStorage) {
        this.whMaxQntyStorage = whMaxQntyStorage;
    }
    public Integer getWhProdQntySold() {
        return this.whProdQntySold;
    }
    
    public void setWhProdQntySold(Integer whProdQntySold) {
        this.whProdQntySold = whProdQntySold;
    }
    public Set<WholesaleOrders> getWholesaleOrderses() {
        return this.wholesaleOrderses;
    }
    
    public void setWholesaleOrderses(Set<WholesaleOrders> wholesaleOrderses) {
        this.wholesaleOrderses = wholesaleOrderses;
    }




}


