package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * WholesaleProducts generated by hbm2java
 */
public class WholesaleProducts  implements java.io.Serializable {


     private Long whProdId;
     private String whProdName;
     private String whProdDesc;
     private String whProdCatg;
     private String whSubCatg;
     private Long whDependProdId;
     private Long rtProdId;
     private Set<WholesalerProductsStock> wholesalerProductsStocks = new HashSet<WholesalerProductsStock>(0);

    public WholesaleProducts() {
    }

    public WholesaleProducts(String whProdName, String whProdDesc, String whProdCatg, String whSubCatg, Long whDependProdId, Long rtProdId, Set<WholesalerProductsStock> wholesalerProductsStocks) {
       this.whProdName = whProdName;
       this.whProdDesc = whProdDesc;
       this.whProdCatg = whProdCatg;
       this.whSubCatg = whSubCatg;
       this.whDependProdId = whDependProdId;
       this.rtProdId = rtProdId;
       this.wholesalerProductsStocks = wholesalerProductsStocks;
    }
   
    public Long getWhProdId() {
        return this.whProdId;
    }
    
    public void setWhProdId(Long whProdId) {
        this.whProdId = whProdId;
    }
    public String getWhProdName() {
        return this.whProdName;
    }
    
    public void setWhProdName(String whProdName) {
        this.whProdName = whProdName;
    }
    public String getWhProdDesc() {
        return this.whProdDesc;
    }
    
    public void setWhProdDesc(String whProdDesc) {
        this.whProdDesc = whProdDesc;
    }
    public String getWhProdCatg() {
        return this.whProdCatg;
    }
    
    public void setWhProdCatg(String whProdCatg) {
        this.whProdCatg = whProdCatg;
    }
    public String getWhSubCatg() {
        return this.whSubCatg;
    }
    
    public void setWhSubCatg(String whSubCatg) {
        this.whSubCatg = whSubCatg;
    }
    public Long getWhDependProdId() {
        return this.whDependProdId;
    }
    
    public void setWhDependProdId(Long whDependProdId) {
        this.whDependProdId = whDependProdId;
    }
    public Long getRtProdId() {
        return this.rtProdId;
    }
    
    public void setRtProdId(Long rtProdId) {
        this.rtProdId = rtProdId;
    }
    public Set<WholesalerProductsStock> getWholesalerProductsStocks() {
        return this.wholesalerProductsStocks;
    }
    
    public void setWholesalerProductsStocks(Set<WholesalerProductsStock> wholesalerProductsStocks) {
        this.wholesalerProductsStocks = wholesalerProductsStocks;
    }




}


