package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WholesaleDelivery generated by hbm2java
 */
public class WholesaleDelivery  implements java.io.Serializable {


     private Long whDeliveryId;
     private WholesaleOrders wholesaleOrders;
     private Date whDeliveryDate;
     private Integer whNoOfDays;

    public WholesaleDelivery() {
    }

	
    public WholesaleDelivery(WholesaleOrders wholesaleOrders) {
        this.wholesaleOrders = wholesaleOrders;
    }
    public WholesaleDelivery(WholesaleOrders wholesaleOrders, Date whDeliveryDate, Integer whNoOfDays) {
       this.wholesaleOrders = wholesaleOrders;
       this.whDeliveryDate = whDeliveryDate;
       this.whNoOfDays = whNoOfDays;
    }
   
    public Long getWhDeliveryId() {
        return this.whDeliveryId;
    }
    
    public void setWhDeliveryId(Long whDeliveryId) {
        this.whDeliveryId = whDeliveryId;
    }
    public WholesaleOrders getWholesaleOrders() {
        return this.wholesaleOrders;
    }
    
    public void setWholesaleOrders(WholesaleOrders wholesaleOrders) {
        this.wholesaleOrders = wholesaleOrders;
    }
    public Date getWhDeliveryDate() {
        return this.whDeliveryDate;
    }
    
    public void setWhDeliveryDate(Date whDeliveryDate) {
        this.whDeliveryDate = whDeliveryDate;
    }
    public Integer getWhNoOfDays() {
        return this.whNoOfDays;
    }
    
    public void setWhNoOfDays(Integer whNoOfDays) {
        this.whNoOfDays = whNoOfDays;
    }




}


