package som.domain;
// Generated Aug 5, 2010 11:05:49 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Wholesaler generated by hbm2java
 */
public class Wholesaler  implements java.io.Serializable {


     private Long whId;
     private String whName;
     private String whAddress;
     private String whCity;
     private String whContactNo;
     private String whEmail;
     private Set<WholesalerProductsStock> wholesalerProductsStocks = new HashSet<WholesalerProductsStock>(0);

    public Wholesaler() {
    }

    public Wholesaler(String whName, String whAddress, String whCity, String whContactNo, String whEmail, Set<WholesalerProductsStock> wholesalerProductsStocks) {
       this.whName = whName;
       this.whAddress = whAddress;
       this.whCity = whCity;
       this.whContactNo = whContactNo;
       this.whEmail = whEmail;
       this.wholesalerProductsStocks = wholesalerProductsStocks;
    }
   
    public Long getWhId() {
        return this.whId;
    }
    
    public void setWhId(Long whId) {
        this.whId = whId;
    }
    public String getWhName() {
        return this.whName;
    }
    
    public void setWhName(String whName) {
        this.whName = whName;
    }
    public String getWhAddress() {
        return this.whAddress;
    }
    
    public void setWhAddress(String whAddress) {
        this.whAddress = whAddress;
    }
    public String getWhCity() {
        return this.whCity;
    }
    
    public void setWhCity(String whCity) {
        this.whCity = whCity;
    }
    public String getWhContactNo() {
        return this.whContactNo;
    }
    
    public void setWhContactNo(String whContactNo) {
        this.whContactNo = whContactNo;
    }
    public String getWhEmail() {
        return this.whEmail;
    }
    
    public void setWhEmail(String whEmail) {
        this.whEmail = whEmail;
    }
    public Set<WholesalerProductsStock> getWholesalerProductsStocks() {
        return this.wholesalerProductsStocks;
    }
    
    public void setWholesalerProductsStocks(Set<WholesalerProductsStock> wholesalerProductsStocks) {
        this.wholesalerProductsStocks = wholesalerProductsStocks;
    }




}


